"""
Tests for helpers.py
"""


import datetime
import hashlib
from unittest.mock import Mock, patch
from zoneinfo import ZoneInfo

from django.test import TestCase

from common.djangoapps.student.tests.factories import UserFactory
from openedx.core.djangolib.testing.utils import skip_unless_lms

from ..image_helpers import get_profile_image_urls_for_user

TEST_SIZES = {'full': 50, 'small': 10}
TEST_PROFILE_IMAGE_UPLOAD_DT = datetime.datetime(2002, 1, 9, 15, 43, 1, tzinfo=ZoneInfo("UTC"))
_GENERATE_INITIALS_PATH = 'openedx.core.djangoapps.profile_images.images.generate_initials_image'


@patch.dict('django.conf.settings.PROFILE_IMAGE_SIZES_MAP', TEST_SIZES, clear=True)
@skip_unless_lms
class ProfileImageUrlTestCase(TestCase):
    """
    Tests for profile image URL generation helpers.
    """

    def setUp(self):
        super().setUp()
        self.user = UserFactory()
        # Ensure that parental controls don't apply to this user
        self.user.profile.year_of_birth = 1980
        self.user.profile.profile_image_uploaded_at = TEST_PROFILE_IMAGE_UPLOAD_DT
        self.user.profile.save()  # pylint: disable=no-member

    def verify_url(self, actual_url, expected_name, expected_pixels, expected_version):
        """
        Verify correct url structure.
        """
        expected = 'http://example-storage.com/profile-images/{name}_{size}.jpg?v={version}'.format(
            name=expected_name, size=expected_pixels, version=expected_version,
        )
        self.assertEqual(actual_url, expected)

    def verify_urls(self, actual_urls, expected_name):
        """
        Verify correct url dictionary structure for an uploaded profile image.
        """
        assert set(TEST_SIZES.keys()) == set(actual_urls.keys())
        for size_display_name, url in actual_urls.items():
            self.verify_url(
                url, expected_name, TEST_SIZES[size_display_name], TEST_PROFILE_IMAGE_UPLOAD_DT.strftime("%s")
            )

    def test_get_profile_image_urls(self):
        """
        Tests `get_profile_image_urls_for_user` when the user has an uploaded image.
        """
        self.user.profile.profile_image_uploaded_at = TEST_PROFILE_IMAGE_UPLOAD_DT
        self.user.profile.save()  # pylint: disable=no-member
        expected_name = hashlib.md5((
            'secret' + str(self.user.username)).encode('utf-8')).hexdigest()
        mock_storage = Mock()
        mock_storage.url.side_effect = lambda filename: f'http://example-storage.com/profile-images/{filename}'
        with patch(
            'openedx.core.djangoapps.user_api.accounts.image_helpers.get_profile_image_storage',
            return_value=mock_storage,
        ):
            actual_urls = get_profile_image_urls_for_user(self.user)
        self.verify_urls(actual_urls, expected_name)

    def test_get_profile_image_urls_default_uses_initials_avatar(self):
        """
        When the user has no uploaded image, URLs are generated by generate_initials_image.
        """
        self.user.profile.profile_image_uploaded_at = None
        self.user.profile.save()  # pylint: disable=no-member

        expected_urls = {size: f'/avatars/{size}.jpg' for size in TEST_SIZES}
        with patch(_GENERATE_INITIALS_PATH, return_value=expected_urls) as mock_gen:
            actual_urls = get_profile_image_urls_for_user(self.user)

        mock_gen.assert_called_once_with(self.user.username, self.user.profile.name)
        assert actual_urls == expected_urls
